# Generated by Django 3.2.9 on 2021-11-15 23:57

from django.db import migrations, models
import eseven.models


class Migration(migrations.Migration):

    dependencies = [
        ('eseven', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=eseven.models.get_image_path),
        ),
    ]
