# Generated by Django 3.2.9 on 2021-11-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eseven', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
