# Generated by Django 3.2.9 on 2021-11-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eseven', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
