# Generated by Django 3.2.9 on 2021-11-18 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eseven', '0003_auto_20211118_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
