# Generated by Django 3.2.9 on 2021-11-18 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eseven', '0004_auto_20211118_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
