# Generated by Django 3.2.9 on 2021-11-18 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eseven', '0005_alter_link_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eseven.link', to_field='code'),
        ),
    ]
